techstuff/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.poll, name='poll'),
]

techstuff/techstuff/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

techstuff/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

techstuff/polls/views.py
from django.shortcuts import render, get_object_or_404

from .models import Question, Choice

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
    
def poll(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        selected_choice_id = request.POST.get('choice','')
        if selected_choice_id.isdigit():
            choice = get_object_or_404(Choice, pk=selected_choice_id)
            choice.votes += 1
            choice.save()
    context = {'question': question}
    return render(request, 'polls/poll.html', context)

techstuff/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

techstuff/polls/templates/polls/poll.html
<h1>{{ question.question_text }}</h1>

<hr>
    {% for choice in question.choice_set.all %}
        {{ choice.choice_text }}: <b>{{ choice.votes }}</b> votes<br />
    {% endfor %}
<hr>

<h2>Add Your Vote</h2>

<form method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <label>
            <input type="radio" name="choice" value="{{ choice.id }}" />
            {{ choice.choice_text }}
        </label>
        <br />
    {% endfor %}
    
    <br />
    <input type="submit" value="Vote">
</form>